security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm:           sha256
            encode_as_base64:    true
            iterations:          5000

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /

            logout:
              path: /logout
              target: /login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/products/add, role: ROLE_ADMIN }
        - { path: ^/products/edit, role: ROLE_ADMIN }
        - { path: ^/products/delete, role: ROLE_ADMIN }
        - { path: ^/products/categories/add, role: ROLE_ADMIN }
        - { path: ^/products/categories/edit, role: ROLE_ADMIN }
        - { path: ^/products/categories/delete, role: ROLE_ADMIN }
        - { path: ^/sales/edit, role: ROLE_ADMIN }
        - { path: ^/sales/delete, role: ROLE_ADMIN }
        - { path: ^/sales/bilan, role: ROLE_ADMIN }
        - { path: ^/products/total, role: ROLE_ADMIN }

