<?php

namespace SalesBundle\Repository;

/**
 * SaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDate($bilan) {
        $qb = $this->createQueryBuilder('s')
            ->leftJoin('s.product', 'p')
            ->addSelect('SUM(p.price*s.quantity) as total_vente')
            ->addSelect('SUM(p.origin_price*s.quantity) as total_achat')
            ->addSelect('SUM(s.quantity) as total_quantity')
            ->groupBy('p.name')
            ->where('s.saleDate >= :start AND s.saleDate <= :finish')
                ->setParameter('start', $bilan->getStartDate())
                ->setParameter('finish', $bilan->getFinishDate());


        return $qb->getQuery()->getResult();
    }
}
